language: node_js
sudo: false
env:
- CXX=g++-4.8
node_js:
- '5'
before_install:
- echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
cache:
  directories:
  - node_modules
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: "trh-test"
  skip_cleanup: true
  acl: public_read
  local_dir: dist
  upload-dir: $TRAVIS_REPO_SLUG/$TRAVIS_BRANCH
