language: node_js
sudo: false
node_js:
- '6'
before_install:
- echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
cache:
  directories:
  - node_modules
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: trh-landing
  skip_cleanup: true
  acl: public_read
  local_dir: dist
  upload-dir: $TRAVIS_REPO_SLUG/$TRAVIS_BRANCH
  on:
    all_branches: true
